stages:
  - ".pre"
  - delete-old-containers
  - prepare-new-images
  - delete-old-images
  - start-new-containers
  - ".post"
delete-old-containers:
  stage: delete-old-containers
  tags:
    - shell
  script:
    - docker rm $(docker ps -aq) -f
prepare-new-images:
  stage: prepare-new-images
  tags:
    - shell
  script:
    - mvn clean package dockerfile:build -DskipTests=true
delete-old-images:
  stage: delete-old-images
  tags:
    - shell
  script:
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
start-new-containers:
  stage: start-new-containers
  tags:
    - shell
  script:
    - docker-compose up -d