stages:
  - ".pre"
  - deploy
  - ".post"
deploy-job:
  stage: deploy
  script:
    - docker rm $(docker ps -aq) -f
    - mvn clean package dockerfile:build -DskipTests=true
    - docker-compose up -d
