stages:
  - ".pre"
  - delete-old-containers
  - prepare-new-images
  - start-new-containers
  - ".post"
delete-old-containers:
  stage: delete-old-containers
  script:
    - docker rm $(docker ps -aq) -f
prepare-new-images:
  stage: prepare-new-images
  script:
    - mvn clean package dockerfile:build -DskipTests=true
start-new-containers:
  stage: start-new-containers
  script:
    - docker-compose up -d
