version: '3'

networks:
  web:
    external: true
    driver: bridge

services:

  db:
    image: "postgres:alpine"
    container_name: db
    volumes:
      - mock-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      web:
        aliases:
          - db
    environment:
      POSTGRES_DB: mock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: ms/app:1
    networks:
      web:
        aliases:
          - app
    ports:
      - "8080:8080"
    links:
      - api
      - q
    depends_on:
      - api
      - q

  api:
    image: ms/api:1
    environment:
      DB_SERVER: db
      POSTGRES_DB: mock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      spring_profiles_active: dev
    networks:
      web:
        aliases:
          - api
    ports:
      - "8082:8082"
    links:
      - db
    depends_on:
      - db

  q:
    image: ms/q:1
    environment:
      DB_SERVER: db
      POSTGRES_DB: mock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      spring_profiles_active: dev
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    networks:
      web:
        aliases:
          - q
    ports:
      - "8081:8081"
    links:
      - db
      - rabbitmq
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    networks:
      web:
        aliases:
          - rabbitmq

volumes:
  mock-data:
