name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Delete old containers
        run: docker rm -vf $(docker ps -aq)
      - name: Delete unused images
        run: docker image prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Prepare new images
        run: mvn clean package dockerfile:build -DskipTests=true
      - name: docker-compose
        run: docker-compose up -d