# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy buy runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
  Delete-old-containers:
    runs-on: self-hosted
    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
      - name: Delete old containers
        run: docker rm $(docker ps -aq) -f
  Create-new-images:
    runs-on: self-hosted
    steps:
      - name: Create new images
        run: mvn clean package dockerfile:build -DskipTests=true
  Delete-old-images:
    runs-on: self-hosted
    steps:
      - name: Delete old images
        run: docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
  Start-new-containers:
    runs-on: self-hosted
    steps:
      - name: Delete old images
        run: docker-compose up -d
